# Generated by Django 5.1.3 on 2024-11-29 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listaempleados', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajador',
            name='user',
        ),
    ]
